import * as data from "./data";
const { recipes } = data;
console.log(recipes);
let arraycakes = recipes.cakes;
console.log(arraycakes);
let arraybreads = recipes.bread;
console.log(arraybreads);
let arraybiscuite = recipes.biscuits;
console.log(arraybiscuite);
let sectionCake = document.getElementById("cakes");
let createElementCakes = arraycakes.map((element) => {
  let div = document.createElement("div");
  div.style.marginBottom = "30px";
  div.style.margin = "10px 5px";
  div.style.border = "1px solid black";
  let image = document.createElement("img");
  image.src = element.image;
  image.width = "100px";
  image.height = "120px";
  let title = document.createElement("p");
  title.style.textAlign = "center";
  console.log(element.author);
  title.innerHTML = element.title;
  title.style.fontSize = "20px";
  let author = document.createElement("p");
  author.style.paddingLeft = "5px";
  author.innerHTML = element.author;
  let line = document.createElement("p");
  line.innerHTML = "_____________";
  let ingredientTxt = document.createElement("p");
  ingredientTxt.innerHTML = "ingredients:";
  ingredientTxt.style.paddingLeft = "5px";
  let ingredients = document.createElement("p");
  ingredients.style.paddingLeft = "5px";
  ingredients.style.paddingRight = "5px";
  ingredients.innerHTML = element.ingredients;
  div.append(image, title, author, line, ingredientTxt, ingredients);
  return div;
});
console.log(createElementCakes);
createElementCakes.forEach((item) => sectionCake.appendChild(item));
